apiVersion: v1
kind: Service
metadata:
  name: treehouse-service
spec:
  selector:
    app: treehouse
  ports:
    - protocol: TCP
      port: 7860       # 对外暴露的端口
      targetPort: 7860 # 转发给容器内部的端口
  type: LoadBalancer   # 允许外部浏览器访问